import { defineStore } from "pinia";

export const useProductStore = defineStore("product", {
  state: () => ({
    products: [
      {
        id: 1,
        name: "Assorted Coffee",
        linkName: "Assorted-Coffee",
        category: "Groceries",
        img: "/images/coffee-asorted-400x400.jpg",
        alt: "Pack of assorted coffee jars.",
        price: "£35.00",
        bestselling: true,
        trending: true,
        onSale: true,
        quantity: 0,
      },
      {
        id: 2,
        name: "Cashew Butter",
        linkName: "Cashew-Butter",
        category: "Groceries",
        img: "/images/cashew-butter-500-300x300.jpg",
        alt: "Jar of cashew butter.",
        price: "£25.00",
        originalPrice: "£35.00",
        bestselling: false,
        trending: false,
        onSale: false,
        quantity: 0,
      },
      {
        id: 3,
        name: "Diabetic Cookies",
        linkName: "Diabetic-Cookies",
        category: "Groceries",
        img: "/images/diabetic-cookies-400x400.jpg",
        alt: "Box of diabetic-friendly cookies.",
        price: "£25.00",
        originalPrice: "£35.00",
        bestselling: false,
        trending: false,
        onSale: false,
        quantity: 0,
      },
      {
        id: 4,
        name: "Farm Fresh Eggs",
        linkName: "Farm-Fresh-Eggs",
        category: "Juice",
        img: "/images/eggs-400x400.jpg",
        alt: "Tray of farm fresh eggs.",
        price: "£34.00",
        bestselling: false,
        trending: false,
        onSale: false,
        quantity: 0,
      },
      {
        id: 5,
        name: "Fresh Orange Juice",
        linkName: "Fresh-Orange-Juice",
        category: "Juice",
        img: "/images/orage-juice-kariz-400x400.jpg",
        alt: "Bottle of fresh orange juice.",
        price: "£18.00",
        bestselling: false,
        trending: false,
        onSale: false,
        quantity: 0,
      },
      {
        id: 6,
        name: "Fresh Organic Honey",
        linkName: "Fresh-Organic-Honey",
        category: "Groceries",
        img: "/images/organic-honey-400x400.jpg",
        alt: "Jar of organic honey.",
        price: "£34.00",
        bestselling: false,
        trending: false,
        onSale: false,
        quantity: 0,
      },
      {
        id: 7,
        name: "Hand Sanitizer",
        linkName: "Hand-Sanitizer",
        category: "Groceries",
        img: "/images/sanitizer-400x400.jpg",
        alt: "Bottle of hand sanitizer.",
        price: "£15.00",
        bestselling: true,
        trending: true,
        onSale: true,
        quantity: 0,
      },
      {
        id: 8,
        name: "Handpicked Red Chillies",
        linkName: "Handpicked-Red-Chillies",
        category: "Groceries",
        img: "/images/red-chillies-400x400.jpg",
        alt: "Bag of handpicked red chillies.",
        price: "£19.00",
        bestselling: true,
        trending: true,
        onSale: false,
        quantity: 0,
      },
      {
        id: 9,
        name: "Natural Extracted Edible Oil",
        linkName: "Natural-Extracted-Edible-Oil",
        category: "Groceries",
        img: "/images/edible-oil-400x400.jpg",
        alt: "Bottle of naturally extracted edible oil.",
        price: "£35.00",
        bestselling: true,
        trending: true,
        onSale: true,
        quantity: 0,
      },
      {
        id: 10,
        name: "Organic Face Scrub",
        linkName: "Organic-Face-Scrub",
        category: "Groceries",
        img: "/images/face-wash-400x400.jpg",
        alt: "Tube of organic face scrub.",
        price: "£20.00",
        bestselling: false,
        trending: false,
        onSale: false,
        quantity: 0,
      },
      {
        id: 11,
        name: "Pulses From Organic Farm",
        linkName: "Pulses-From-Organic-Farm",
        category: "Groceries",
        img: "/images/pulses.jpg",
        alt: "Bag of organic farm pulses.",
        price: "£15.00",
        bestselling: false,
        trending: false,
        onSale: false,
        quantity: 0,
      },
      {
        id: 12,
        name: "Wheat From Organic Farms",
        linkName: "Wheat-From-Organic-Farms",
        category: "Groceries",
        img: "/images/wheat-400x400.jpg",
        alt: "Bag of organic farm wheat.",
        price: "£34.00",
        bestselling: false,
        trending: false,
        onSale: false,
        quantity: 0,
      },
    ],
  }),
  getters: {
    // best selling products
    bestselling(state) {
      return state.products.filter((product) => product.bestselling);
    },
    // trending products
    trending(state) {
      return state.products.filter((product) => product.trending);
    },
  },
  actions: {},
});
